export const SHOW_SIGN_IN = 'SHOW_SIGN_IN'
export const HIDE_SIGN_IN = 'HIDE_SIGN_IN'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const SHOW_SIGN_UP = 'SHOW_SIGN_UP'
export const HIDE_SIGN_UP = 'HIDE_SIGN_UP'
export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const SHOW_MEMBERSHIP = 'SHOW_MEMBERSHIP'
export const HIDE_MEMBERSHIP = 'HIDE_MEMBERSHIP'
export const MEMBERSHIP = 'MEMBERSHIP'
export const MEMBERSHIP_SUCCESS = 'MEMBERSHIP_SUCCESS'
export const MEMBERSHIP_FAILURE = 'MEMBERSHIP_FAILURE'

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE'

export const SET_SESSION = 'SET_SESSION'
export const RESET_SESSION = 'RESET_SESSION'

export const SET_TOAST = 'SET_TOAST'
export const RESET_TOAST = 'RESET_TOAST'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE'

export const SUBMIT_BILLING_INFO = 'SUBMIT_BILLING_INFO'
export const SUBMIT_BILLING_INFO_SUCCESS = 'SUBMIT_BILLING_INFO_SUCCESS'
export const SUBMIT_BILLING_INFO_FAILURE = 'SUBMIT_BILLING_INFO_FAILURE'

export const GET_BILLING_INFO = 'GET_BILLING_INFO'
export const GET_BILLING_INFO_SUCCESS = 'GET_BILLING_INFO_SUCCESS'
export const GET_BILLING_INFO_FAILURE = 'GET_BILLING_INFO_FAILURE'

export const UPDATE_BILLING_INFO = 'UPDATE_BILLING_INFO'
export const UPDATE_BILLING_INFO_SUCCESS = 'UPDATE_BILLING_INFO_SUCCESS'
export const UPDATE_BILLING_INFO_FAILURE = 'UPDATE_BILLING_INFO_FAILURE'

export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS'
export const GET_ALL_POSTS_FAILURE = 'GET_ALL_POSTS_FAILURE'

export const GET_POST_DETAILS = 'GET_POST_DETAILS'
export const GET_POST_DETAILS_SUCCESS = 'GET_POST_DETAILS_SUCCESS'
export const GET_POST_DETAILS_FAILURE = 'GET_POST_DETAILS_FAILURE'

export const SUBMIT_POST = 'SUBMIT_POST'
export const SUBMIT_POST_SUCCESS = 'SUBMIT_POST_SUCCESS'
export const SUBMIT_POST_FAILURE = 'SUBMIT_POST_FAILURE'

export const GET_OWN_POSTS = 'GET_OWN_POSTS'
export const GET_OWN_POSTS_SUCCESS = 'GET_OWN_POSTS_SUCCESS'
export const GET_OWN_POSTS_FAILURE = 'GET_OWN_POSTS_FAILURE'

export const GET_POST_TO_EDIT = 'GET_POST_TO_EDIT'
export const GET_POST_TO_EDIT_SUCCESS = 'GET_POST_TO_EDIT_SUCCESS'
export const GET_POST_TO_EDIT_FAILURE = 'GET_POST_TO_EDIT_FAILURE'

export const EDIT_POST = 'EDIT_POST'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE'

export const GET_FILTERED_POSTS = 'GET_FILTERED_POSTS'
export const GET_FILTERED_POSTS_SUCCESS = 'GET_FILTERED_POSTS_SUCCESS'
export const GET_FILTERED_POSTS_FAILURE = 'GET_FILTERED_POSTS_FAILURE'

export const GET_ALL_FRANCHISES = 'GET_ALL_FRANCHISES'
export const GET_ALL_FRANCHISES_SUCCESS = 'GET_ALL_FRANCHISES_SUCCESS'
export const GET_ALL_FRANCHISES_FAILURE = 'GET_ALL_FRANCHISES_FAILURE'

export const GET_FRANCHISE_DETAILS = 'GET_FRANCHISE_DETAILS'
export const GET_FRANCHISE_DETAILS_SUCCESS = 'GET_FRANCHISE_DETAILS_SUCCESS'
export const GET_FRANCHISE_DETAILS_FAILURE = 'GET_FRANCHISE_DETAILS_FAILURE'

export const SUBMIT_FRANCHISE = 'SUBMIT_FRANCHISE'
export const SUBMIT_FRANCHISE_SUCCESS = 'SUBMIT_FRANCHISE_SUCCESS'
export const SUBMIT_FRANCHISE_FAILURE = 'SUBMIT_FRANCHISE_FAILURE'

export const GET_OWN_FRANCHISES = 'GET_OWN_FRANCHISES'
export const GET_OWN_FRANCHISES_SUCCESS = 'GET_OWN_FRANCHISES_SUCCESS'
export const GET_OWN_FRANCHISES_FAILURE = 'GET_OWN_FRANCHISES_FAILURE'

export const GET_FRANCHISE_TO_EDIT = 'GET_FRANCHISE_TO_EDIT'
export const GET_FRANCHISE_TO_EDIT_SUCCESS = 'GET_FRANCHISE_TO_EDIT_SUCCESS'
export const GET_FRANCHISE_TO_EDIT_FAILURE = 'GET_FRANCHISE_TO_EDIT_FAILURE'

export const EDIT_FRANCHISE = 'EDIT_FRANCHISE'
export const EDIT_FRANCHISE_SUCCESS = 'EDIT_FRANCHISE_SUCCESS'
export const EDIT_FRANCHISE_FAILURE = 'EDIT_FRANCHISE_FAILURE'

export const GET_FILTERED_FRANCHISES = 'GET_FILTERED_FRANCHISES'
export const GET_FILTERED_FRANCHISES_SUCCESS = 'GET_FILTERED_FRANCHISES_SUCCESS'
export const GET_FILTERED_FRANCHISES_FAILURE = 'GET_FILTERED_FRANCHISES_FAILURE'